version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8096:8096"
    networks:
      - kong-net

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "4200:80"
    networks:
      - kong-net

  kong:
    image: kong:3.5
    container_name: kong
    depends_on:
      - backend
      - frontend
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_LISTEN: 0.0.0.0:8000
    volumes:
      - ./kong/kong.yml:/kong/kong.yml
    ports:
      - "80:8000"
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge
