version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - kong-db-data:/var/lib/postgresql/data
    networks:
      - kong-net

  kong-migrations:
    image: kong:latest
    depends_on:
      - postgres
    entrypoint: kong migrations bootstrap
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_PASSWORD: kong
    networks:
      - kong-net

  kong:
    image: kong:latest
    depends_on:
      - kong-migrations
    ports:
      - "80:8000"
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_PASSWORD: kong
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: off
    volumes:
      - ./kong/kong.yml:/kong/kong.yml
    networks:
      - kong-net

  backend:
    build: ./backend
    expose:
      - "8096"
    networks:
      - kong-net

  frontend:
    build: ./frontend
    expose:
      - "80"
    networks:
      - kong-net

volumes:
  kong-db-data:

networks:
  kong-net:

